/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TodoRouteImport } from './routes/todo'
import { Route as UsersRouteImport } from './routes/users'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DepartmentsIdRouteImport } from './routes/departments.$id'
import { Route as EmployeesIdRouteImport } from './routes/employees.$id'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoRoute = TodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIdRoute = DepartmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DepartmentsRoute,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmployeesRoute,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/employees': typeof EmployeesRouteWithChildren
  '/login': typeof LoginRoute
  '/positions': typeof PositionsRoute
  '/settings': typeof SettingsRoute
  '/todo': typeof TodoRoute
  '/users': typeof UsersRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/employees': typeof EmployeesRouteWithChildren
  '/login': typeof LoginRoute
  '/positions': typeof PositionsRoute
  '/settings': typeof SettingsRoute
  '/todo': typeof TodoRoute
  '/users': typeof UsersRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/employees': typeof EmployeesRouteWithChildren
  '/login': typeof LoginRoute
  '/positions': typeof PositionsRoute
  '/settings': typeof SettingsRoute
  '/todo': typeof TodoRoute
  '/users': typeof UsersRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/attendance'
    | '/dashboard'
    | '/departments'
    | '/employees'
    | '/login'
    | '/positions'
    | '/settings'
    | '/todo'
    | '/users'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/departments/$id'
    | '/employees/$id'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/attendance'
    | '/dashboard'
    | '/departments'
    | '/employees'
    | '/login'
    | '/positions'
    | '/settings'
    | '/todo'
    | '/users'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/departments/$id'
    | '/employees/$id'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/attendance'
    | '/dashboard'
    | '/departments'
    | '/employees'
    | '/login'
    | '/positions'
    | '/settings'
    | '/todo'
    | '/users'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/departments/$id'
    | '/employees/$id'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AttendanceRoute: typeof AttendanceRoute
  DashboardRoute: typeof DashboardRoute
  DepartmentsRoute: typeof DepartmentsRouteWithChildren
  EmployeesRoute: typeof EmployeesRouteWithChildren
  LoginRoute: typeof LoginRoute
  PositionsRoute: typeof PositionsRoute
  SettingsRoute: typeof SettingsRoute
  TodoRoute: typeof TodoRoute
  UsersRoute: typeof UsersRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$id': {
      id: '/departments/$id'
      path: '/$id'
      fullPath: '/departments/$id'
      preLoaderRoute: typeof DepartmentsIdRouteImport
      parentRoute: typeof DepartmentsRoute
    }
    '/employees/$id': {
      id: '/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DepartmentsRouteChildren {
  DepartmentsIdRoute: typeof DepartmentsIdRoute
}

const DepartmentsRouteChildren: DepartmentsRouteChildren = {
  DepartmentsIdRoute: DepartmentsIdRoute,
}

const DepartmentsRouteWithChildren = DepartmentsRoute._addFileChildren(
  DepartmentsRouteChildren,
)

interface EmployeesRouteChildren {
  EmployeesIdRoute: typeof EmployeesIdRoute
}

const EmployeesRouteChildren: EmployeesRouteChildren = {
  EmployeesIdRoute: EmployeesIdRoute,
}

const EmployeesRouteWithChildren = EmployeesRoute._addFileChildren(
  EmployeesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AttendanceRoute: AttendanceRoute,
  DashboardRoute: DashboardRoute,
  DepartmentsRoute: DepartmentsRouteWithChildren,
  EmployeesRoute: EmployeesRouteWithChildren,
  LoginRoute: LoginRoute,
  PositionsRoute: PositionsRoute,
  SettingsRoute: SettingsRoute,
  TodoRoute: TodoRoute,
  UsersRoute: UsersRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
